= Parameters

The parent key for all of the following parameters is `capi_provider_talos`.

== `namespace`

[horizontal]
type:: string
default:: `syn-cluster-api`

The namespace in which to deploy this component.
The component assumes that this namespace already exists via dependency `component-capi-core`.

== `images`

[horizontal]
type:: dict
default:: See `class/defaults.yml`

The default Docker image location and tag to use for the CAPI provider talos components (keys `capi-boostrap-provider-talos` and `capi-controlplane-provider-talos`).

Entries in this dict should be dictionaries with keys `registry`, `image`, and `tag`. This structure provides the basis for dependency maintenance with Renovate.

The values of `capi-bootstrap-provider-talos.tag` and  `capi-controlplane-provider-talos.tag` in this dict is used by the component to select the versions of the upstream CAPI provider talos components.

== `kustomization_urls`

[horizontal]
type:: dict
default:: See `class/defaults.yml`

This parameter allows providing non-standard URLs for each provider's base Kustomization.

The component will look for fields that match the fields in parameter `images` and expects values to be valid Git repository URLs.

NOTE: Currently, the component looks for the Kustomization in a hard-coded path in the provided repository.

== `bootstrap.variables`

[horizontal]
type:: dict
default:: See `class/defaults.yml`

An object with environment variables that the generated manifests of the bootstrap provider will be templated with, similar to `clusterctl`.
Variables should be specified in the format:

[source,yaml]
----
variables:
  FOO: bar
----

== `controlplane.variables`

[horizontal]
type:: dict
default:: See `class/defaults.yml`

An object with environment variables that the generated manifests of the control plane provider will be templated with, similar to `clusterctl`.
variables should be specified in the format:

[source,yaml]
----
variables:
  FOO: bar
----

== Example

[source,yaml]
----
namespace: example-namespace
images:
  capi-bootstrap-provider-talos:
    tag: tag: v0.6.12
  capi-controlplane-provider-talos:
    tag: tag: v0.5.13
bootstrap:
  variables:
      MY_VARIABLE: value
controlplane:
  variables:
      MY_VARIABLE: value
----
